spring:
  application:
    name: inventory-service
server:
  port: 8180
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        # unsafe!
        include: '*'